name: Main Automation
on:
  schedule:
    # Run every 2 hours during business hours (9 AM to 9 PM UTC)
    - cron: '0 9-21/2 * * *'
    # Run every 6 hours during night hours  
    - cron: '0 3,15 * * *'
  
  workflow_dispatch:  # Allow manual trigger
  
  push:
    branches: [ main ]
    paths: 
      - 'fixed_working_code_1.py'
      - '.github/workflows/main.yml'
permissions:
  contents: write
jobs:
  process-podcasts:
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Increased timeout
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install specific versions to avoid conflicts
        pip install "numpy<2.0"
        pip install torch==1.13.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        pip install openai-whisper==20231117
        pip install feedparser==6.0.10 requests==2.31.0 python-dateutil==2.8.2
        
    - name: Create directories
      run: |
        mkdir -p downloads transcripts
    
    # Debug step - Check if secrets are available
    - name: Debug environment variables
      run: |
        echo "Checking environment variables..."
        if [ -z "$MISTRAL_API_KEY" ]; then echo "❌ MISTRAL_API_KEY is missing"; else echo "✅ MISTRAL_API_KEY is set"; fi
        if [ -z "$EMAIL_FROM" ]; then echo "❌ EMAIL_FROM is missing"; else echo "✅ EMAIL_FROM is set"; fi
        if [ -z "$EMAIL_TO" ]; then echo "❌ EMAIL_TO is missing"; else echo "✅ EMAIL_TO is set"; fi
        if [ -z "$EMAIL_PASSWORD" ]; then echo "❌ EMAIL_PASSWORD is missing"; else echo "✅ EMAIL_PASSWORD is set"; fi
      env:
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        
    - name: Run podcast pipeline
      env:
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python fixed_working_code_1.py
        
    - name: Upload artifacts (transcripts)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: transcripts-${{ github.run_number }}
        path: transcripts/
        retention-days: 30
        
    - name: Commit processed episodes log
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -f processed.json ]; then
          git add processed.json
          git diff --staged --quiet || git commit -m "Update processed episodes [skip ci]"
          git push origin main
        fi
        if [ -f emailed.json ]; then
          git add emailed.json
          git diff --staged --quiet || git commit -m "Update emailed episodes [skip ci]"
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
